name: Run all D Tests

on: push

jobs:
  dub-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dc: [dmd-latest, dmd-2.098.1, dmd-2.099.0, ldc-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run tests
        run: dub -b unittest