name: Run all D Tests

on: push

jobs:
  dub-tests:
    strategy:
      matrix:
        os: [macOS-latest]
        dc: [ldc-latest, dmd-2.098.1, dmd-2.099.0, dmd-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2  
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          dc: ${{ matrix.dc }}
      - name: Run tests
        run: dub -b unittest